language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - 0.5
    - nightly
notifications:
    email: false
dist: trusty
sudo: required
#addons:
#    apt_packages:
#        - gfortran
script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install gfortran ; fi
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Ipopt")'
    - julia -e 'Pkg.test("Ipopt", coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("Ipopt")); using Coverage; Coveralls.submit(process_folder())'
